// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNqXkPUH-djEpZtXctwKnZKZwDr2XKTY',
    appId: '1:342292747100:web:845a0c4b840058f7fea799',
    messagingSenderId: '342292747100',
    projectId: 'flutter-login-cfbd7',
    authDomain: 'flutter-login-cfbd7.firebaseapp.com',
    databaseURL: 'https://flutter-login-cfbd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-cfbd7.appspot.com',
    measurementId: 'G-TT6MHEJEYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnvcColg9PF0iKt5lpokKXkgy4ywCsjw',
    appId: '1:342292747100:android:fc02215323a2a4e4fea799',
    messagingSenderId: '342292747100',
    projectId: 'flutter-login-cfbd7',
    databaseURL: 'https://flutter-login-cfbd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-cfbd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuTqkeM-FGmZvOvh5nhVQasGtfyEFngOU',
    appId: '1:342292747100:ios:20f31ce6c373862ffea799',
    messagingSenderId: '342292747100',
    projectId: 'flutter-login-cfbd7',
    databaseURL: 'https://flutter-login-cfbd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-cfbd7.appspot.com',
    androidClientId: '342292747100-22cac4t612s4fdbgdqoiftrurg9lm8jn.apps.googleusercontent.com',
    iosClientId: '342292747100-57jn2fham0c736h9jn365e4130cqknsh.apps.googleusercontent.com',
    iosBundleId: 'com.saidino.sysmanagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuTqkeM-FGmZvOvh5nhVQasGtfyEFngOU',
    appId: '1:342292747100:ios:20f31ce6c373862ffea799',
    messagingSenderId: '342292747100',
    projectId: 'flutter-login-cfbd7',
    databaseURL: 'https://flutter-login-cfbd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-cfbd7.appspot.com',
    androidClientId: '342292747100-22cac4t612s4fdbgdqoiftrurg9lm8jn.apps.googleusercontent.com',
    iosClientId: '342292747100-57jn2fham0c736h9jn365e4130cqknsh.apps.googleusercontent.com',
    iosBundleId: 'com.saidino.sysmanagment',
  );
}
